apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: xinbrtwg6-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/xinbrtwg6-java-quarkus-gitops